version: '3.4'

services:
  countrypublicholidays.api:
    image: "ireallie/countrypublicholidaysapi:latest"
    build:
      context: .
      dockerfile: src/CountryPublicHolidays.Api/Dockerfile
    ports:
     - 5400:80
     - 5401:443
